# Generated by Django 5.1.1 on 2024-09-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='vector', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
