# Generated by Django 5.1.1 on 2024-09-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
