services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      timeout: 10s
      retries: 5

  admin_api:
    build:
      context: ./admin_api
    environment:
      - ENVIRONMENT=docker
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=password
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "7000:7000"
    volumes:
      - .:/app
    command: ["./start.sh"]
    networks:
      - my_network

  frontend_api:
    build:
      context: ./frontend_api
    environment:
      - ENVIRONMENT=docker
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=password
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["./start.sh"]
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
