# Generated by Django 5.1.1 on 2024-09-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book_borrowed_by_book_borrowed_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='date_joined',
        ),
    ]
